Ecommerce Project_complete/Return/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls import url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^order/', include('order.urls')),
    url(r'^$', RedirectView.as_view(url='/order/', permanent=True)),
    url('^accounts/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Ecommerce Project_complete/order/urls.py
from django.conf.urls import url
from django.contrib import admin
from  .import views

app_name = 'order'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9,a-z,\-]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^return_order/add/$', views.ReturnCreate.as_view(), name='add_return'),

    url(r'^return_items/$', views.return_statusView.as_view(), name='return_items'),

    url(r'^all_products/$',views.all_ProductsView.as_view(), name='product_items'),

    url(r'^(products/(?P<proid>[0-9,a-z,\-]+))/$', views.each_product, name='each_product'),

    url(r'^return_order/edit/(?P<pk>[0-9,a-z,\-]+)/$', views.ReturnUpdate.as_view(), name='update_return'),

    url(r'^return_order/delete/(?P<pk>[0-9,a-z,\-]+)/$', views.ReturnDelete.as_view(), name='delete_return')
]

Ecommerce Project_complete/order/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
import uuid

class Orders(models.Model):
    OrderId = models.CharField(max_length=250)
    TimeStamp = models.CharField(max_length=100)
    Address = models.CharField(max_length=500)

class Product(models.Model):
    ProdId = models.CharField(max_length=100)
    PName = models.CharField(max_length=100)
    PType = models.CharField(max_length=250)
    PCat = models.CharField(max_length=100)
    PPrice = models.CharField(max_length=250)
    PQuantity = models.CharField(max_length=250)
    Prourl = models.CharField(max_length=500)
    ProBuyer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.PName

class ProductOrder(models.Model):
    ProdOrderId = models.CharField(max_length=250)
    ReturnStatus = models.CharField(max_length=100)
    OrderQuantity = models.CharField(max_length=500)
    CurrentQuantity = models.CharField(max_length=500)
    TotalPrice = models.CharField(max_length=500)
    OrderId = models.ForeignKey(Orders, on_delete=models.CASCADE)
    ProdId = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.ProdOrderId + "-" + self.Orders.OrderId

class return_order(models.Model):
    ReturnId = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4, primary_key=True)
    RTimeStamp = models.DateTimeField(auto_now_add=True)
    ReturnReason_choices = (
        ('Product Damaged','Product Damaged'),
        ('Item arrived too late','Item arrived too late'),
        ('Missing Parts or accesories','Missing Parts or accesories'),
        ('Product and shipping box both damaged','Product and shipping box both damaged'),
        ('Wrong item sent','Wrong item sent'),
        ('Item defective', 'Item defective'),
        ('Item no longer needed','Item no longer needed'),
    )
    ReturnReason = models.CharField(max_length=500, choices=ReturnReason_choices)
    ReturnOption_choices = (
        ('Cashback','Cashback'),
        ('Replacement','Replacement'),
        ('EKart Credits','EKart Credits'),
    )
    ReturnOptions = models.CharField(max_length=500, choices=ReturnOption_choices)
    #ReturnFeedback = models.CharField(max_length=500)
    ProductId = models.ForeignKey(Product, on_delete=models.CASCADE)
    #ProductName = models.CharField(max_length=500)
    ProductQuality_choices = (
        ('Excellent - Unopened','Excellent - Unopened'),
        ('Good - Slightly Used','Good - Slightly Used'),
        ('Poor - Broken','Poor - Broken')
    )
    ProductQuality = models.CharField(max_length=500, choices=ProductQuality_choices)

    def get_absolute_url(self):
        return reverse ('order:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.ReturnId + "-" + self.RTimeStamp

Ecommerce Project_complete/order/forms.py
from django import forms

from .models import Product, return_order


class return_orderForm(forms.ModelForm):
    class Meta:
        model = return_order
        fields = ('ProductId', 'ReturnReason', 'ReturnOptions', 'ProductQuality')

    def __init__(self, user, *args, **kwargs):
        super(return_orderForm, self).__init__(*args, **kwargs)
        self.fields['ProductId'].queryset = Product.objects.filter(ProBuyer=user)


Ecommerce Project_complete/order/views.py
from django.views import generic
from .models import Orders, Product, ProductOrder, return_order
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import return_orderForm


class IndexView(generic.ListView):
    template_name = 'order/index.html'
    context_object_name = 'all_Return'
    def get_queryset(self):
        return return_order.objects.all()

class DetailView(LoginRequiredMixin,generic.DeleteView):
    model = return_order
    template_name = 'order/detail.html'

class ReturnCreate(LoginRequiredMixin,CreateView):
    form_class = return_orderForm
    template_name = 'order/return_order_form.html'
    #model = return_order
    #fields = ['ProductId', 'ReturnReason', 'ReturnOptions', 'ProductQuality']

    def get_form_kwargs(self):
        kwargs = super(ReturnCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs



class ReturnUpdate(LoginRequiredMixin,UpdateView):
    model = return_order
    fields = ['ProductId', 'ReturnReason', 'ReturnOptions', 'ProductQuality']

class ReturnDelete(LoginRequiredMixin,DeleteView):
    model = return_order
    success_url = reverse_lazy('order:return_items')

# Create your views here.

'''
@login_required
def return_status(request):
    all_Return = return_order.objects.select_related('ProductId')
    all_obj = return_order.objects.select_related('ProductId')
    context = {'all_Return': all_Return,
               'all_obj': all_obj,
               }
    return render(request,'order/return_items_list.html',context)

'''
'''
@login_required
def all_products(request):
    all_products_list = Product.objects.all()
    context = {'all_products_list': all_products_list}
    return render(request, 'order/products_list.html',context)
'''


@login_required
def each_product(request, proid):
    specific_product = Product.objects.get(pk=proid)
    context = {'specific_product': specific_product}
    return render(request, 'order/each_product.html',context)

class all_ProductsView(LoginRequiredMixin,generic.ListView):
    template_name = 'order/products_list.html'
    context_object_name = 'all_products_list'
    def get_queryset(self):
        return Product.objects.filter(ProBuyer=self.request.user)

class return_statusView(LoginRequiredMixin,generic.ListView):
    template_name = 'order/return_items_list.html'
    context_object_name = 'all_Return'
    def get_queryset(self):
        return return_order.objects.select_related('ProductId').filter(ProductId__ProBuyer=self.request.user)

Ecommerce Project_complete/order/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ekart</title>
     {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'order/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'order:index' %}" style="font-family:'Lobster'">EKart</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">About us</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Returns <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'order:add_return' %}">Return an item</a></li>
            <li><a href="#">Update a Return</a></li>
            <li><a href="#">Withdraw a return</a></li>
            <li><a href="{% url 'order:return_items' %}">Track Return Status</a></li>
          </ul>
        </li>
        <li><a href="{% url 'order:product_items' %}">Products</a></li>
        <li><a href="#">Orders</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="{% url 'login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

Ecommerce Project_complete/order/templates/order/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ekart</title>
     {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'order/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'order:index' %}" style="font-family:'Lobster'">EKart</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">About us</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Returns <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'order:add_return' %}">Return an item</a></li>
            <li><a href="#">Update a Return</a></li>
            <li><a href="#">Withdraw a return</a></li>
            <li><a href="{% url 'order:return_items' %}">Track Return Status</a></li>
          </ul>
        </li>
        <li><a href="{% url 'order:product_items' %}">Products</a></li>
        <li><a href="#">Orders</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout'%}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

Ecommerce Project_complete/order/templates/order/detail.html
{% extends 'order/base.html' %}

{% block body %}

<div class="container">
    <h1>Return Information</h1>
    <table class="table table-striped">
        <tr>
            <th></th>
            <th>Product Information</th>
        </tr>
        <tr>
            <td>Product Name</td>
            <td>{{return_order.ProductId}}</td>
        </tr>
        <tr>
            <td>Timestamp</td>
            <td>{{return_order.RTimeStamp}}</td>
        </tr>
        <tr>
            <td>Return Reason</td>
            <td>{{return_order.ReturnReason}} </td>
        </tr>
            <td>Return Feedback</td>
            <td>{{return_order.ReturnOptions}} </td>
        </tr>
        <tr>
            <td>Product Quality</td>
            <td>{{return_order.ProductQuality}}</td>
        </tr>
    </table>
    <h3><a href="{% url 'order:return_items' %}">Back to Return Page</a> </h3>
</div>

{% endblock %}

Ecommerce Project_complete/order/templates/order/each_product.html
{% extends 'order/base.html' %}
{% block body %}


<div class="jumbotron jumbotron-fluid text-center">
    <h1> Deatails of the product </h1>
</div>

<div class="container text-center">
    <div class="row text-center">
        <div class="col-md-4"></div>
        <div class="col-md-4">
                <h3>{{specific_product.PName}} </h3>
                <img src="{{specific_product.Prourl}}" class="img-rounded" height="100" width="100">
                <h1></h1>
                <h4><em>Price </em>{{specific_product.PPrice}}</h4>
                <h4><em>Quantity </em>{{specific_product.PQuantity}}</h4>
             </div>
        <div class="col-md-4"></div>
    </div>
</div>

{% endblock %}

Ecommerce Project_complete/order/templates/order/form-template.html

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>

        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

Ecommerce Project_complete/order/templates/order/index.html
{% extends 'base_generic.html' %}
{% block body %}
{% endblock %}

Ecommerce Project_complete/order/templates/order/products_list.html
{% extends 'order/base.html' %}
{% block body %}

<div class="jumbotron jumbotron-fluid text-center">
    <h1> Products you have bought </h1>
</div>

<div class="container text-center">
    <div class="row text-center">
        {% for product_order in all_products_list %}
            <div class="col-md-4">
                <a href ="/order/products/{{product_order.ProdId}}"><h3>{{product_order.PName}} </h3></a>
                <img src="{{product_order.Prourl}}" class="img-rounded" height="100" width="100">
                <h1></h1>
                <h4><em>Price </em>{{product_order.PPrice}}</h4>
                <h4><em>Quantity </em>{{product_order.PQuantity}}</h4>
             </div>
        {% endfor %}
    </div>
</div>

{% endblock %}


Ecommerce Project_complete/order/templates/order/return_items_list.html
{% extends 'order/base.html' %}
{% block body %}

    <div class="jumbotron jumbotron-fluid text-center">
    <h1> Welcome to the Return Page </h1>
    </div>

<div class="container text-center">
    <div class="row text-center">
        {% for return_order in all_Return %}
        <div class="col-md-4">
        <img src="{{return_order.ProductId.Prourl}}" height="100" width="100">
        <br><br>
        <b><a href="{% url 'order:detail' return_order.ReturnId %}"> {{return_order.ProductId}} </a></b>
        </br>
        <a href="{% url 'order:update_return' return_order.ReturnId %}"> Update </a>
        </br>
        <form action="{% url 'order:delete_return' return_order.ReturnId %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="return_id" value="{{return_order.ReturnId}}"/>
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span>
            </button>

        <br><br>
        </form>
        </div>
        {% endfor %}
    </div>

    <footer class="footer">
      <div class="container">
        <h2><a href="{% url 'order:add_return' %}">Add Return</a> </h2>
      </div>
    </footer>
</div>


</div>
{% endblock %}

Ecommerce Project_complete/order/templates/order/return_order_form.html
{% extends 'order/base.html' %}
{% block body %}

<div class="container">
    <h2>Enter Product Details</h2>
    <form action="", method="post">
    {% csrf_token %}
    {% include 'order/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

</div>

{% endblock %}